import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
const workspaceDir=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const SKILL_DIR='/root/.codex/skills/builtins/presentations';
const {applyPresentationChartFont,finalizePresentation}=await import(pathToFileURL(path.join(SKILL_DIR,'container_tools/artifact_tool_utils.mjs')).href);
const data=JSON.parse(await fs.readFile(path.join(workspaceDir,'results/deck-data.json'),'utf8'));
const {summary:s,interpretation:i,profiles:p,stability:st}=data;
const P=Presentation.create({slideSize:{width:1280,height:720}});const family='DejaVu Sans';
const green='#157F6B',ink='#24362D',muted='#65796F';
const colors=['#157F6B','#3D64B1','#D78F38','#AB4E71','#8665B4','#367B94','#788039'];
const src='Источники: СберИндекс, официальный архив hackathonlicence.zip, CC BY-SA 4.0, скачан 07.10.2026. Собственные расчёты.';
function txt(slide,text,x,y,w,h,size=28,bold=false,color=ink){let q=slide.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});q.text=text;q.text.style={typeface:family,fontSize:size,bold,color,autoFit:'none'};return q;}
function slide(title,sub=''){let sl=P.slides.add();sl.background.fill='#FFFFFF';txt(sl,title,65,48,1140,85,42,true,green);if(sub)txt(sl,sub,65,142,1140,64,23,false,muted);txt(sl,'Экономический отпечаток · Кластеризация · 2026',65,676,1040,25,15,false,muted);txt(sl,String(P.slides.items.length).padStart(2,'0'),1160,676,55,25,15,false,muted);sl.speakerNotes.textFrame.setText(src);return sl;}
function chart(sl,type,categories,series,extra={}){let ch=sl.charts.add(type,{position:{left:75,top:230,width:1120,height:380},categories,series:series.map(q=>({...q,values:q.values.map(v=>Number(v.toFixed(6)))})),hasLegend:series.length>1,legend:{position:'bottom',textStyle:{fontSize:18}},chartFill:'#FFFFFF',plotAreaFill:'#FFFFFF',...extra});applyPresentationChartFont(ch,{fontFamily:family});ch.xAxis={...extra.xAxis,textStyle:{typeface:family,fontSize:18},numberFormatCode:'0.0'};ch.yAxis={...extra.yAxis,textStyle:{typeface:family,fontSize:18},numberFormatCode:'0.0'};return ch;}
let sl=slide('Экономический отпечаток\nмуниципалитетов');txt(sl,'Динамические сети потребительских профилей',65,245,1060,70,34);txt(sl,'2 016 территорий · 24 месяца · 7 групп в декабре 2024',65,370,1080,65,32,true);txt(sl,'Реальные данные СберИндекса. Воспроизводимый анализ.\nУстойчивые ядра и пограничные случаи.',65,475,1080,100,27);txt(sl,'Конкурс СберИндекса · Направление «Кластеризация»',65,605,1080,45,22,false,muted);
sl=slide('Данные и границы анализа','Январь 2023 — декабрь 2024. Средние безналичные расходы жителей МО.');txt(sl,'303 126 исходных строк\n2 190 территориальных идентификаторов\n2 016 территорий с полными рядами\n174 территории исключены из полной панели',65,235,670,245,30);txt(sl,'Пропуски не заменяются нулями.\nterritory_id задаёт постоянные границы.\nОбщий уровень расходов отделён от структуры.',65,520,1080,105,25);txt(sl,'Дополнительная проверка:\nдоступность рынков за 2024\nи дорожные расстояния',800,240,395,180,29,true,green);txt(sl,'Данные и производные результаты\nCC BY-SA 4.0',800,455,395,80,24,false,muted);
sl=slide('Признаки потребительского профиля','Шесть непересекающихся долей, сумма равна единице.');txt(sl,'Продовольствие, здоровье, маркетплейсы,\nобщественное питание, транспорт, прочие расходы.',65,235,1110,95,30);txt(sl,'p = расход категории / расход по всем категориям\nx = √p̄\nH = ||xᵢ − xⱼ||₂ / √2',65,365,1090,155,33,true,green);txt(sl,'p̄ — среднее месячных долей за последние шесть месяцев.\nБудущие наблюдения не используются. Окна 1 и 3 месяца проверены отдельно.',65,555,1120,85,24);sl.speakerNotes.textFrame.setText(src+' Прочие расходы — остаток общей категории после пяти опубликованных компонентов. Первые пять месяцев — расширяющееся окно.');
sl=slide('Экономическая сеть','Union-kNN: 12 ближайших соседей. Ребро отражает сходство расходов.');sl.images.add({blob:new Uint8Array(await fs.readFile(path.join(workspaceDir,'results/figures/network.png'))),contentType:'image/png',alt:'PCA профилей и 700 наиболее весомых рёбер декабря 2024',fit:'contain',position:{left:80,top:215,width:810,height:425}});txt(sl,'wᵢⱼ = exp(−d² / σᵢσⱼ)\n\nСамопетли исключены.\nЛокальная шкала весов.\n\nЭто сходство, а не\nнаблюдаемые потоки.',930,270,300,320,24);sl.speakerNotes.textFrame.setText(src+' Показаны все 2016 узлов и 700 наиболее весомых рёбер; координаты в фиксированном PCA-базисе января 2023, не карта. Метод: Leiden RBConfiguration, gamma=.5 выбран по SW в июне–августе2023 при минимальной группе20.');
sl=slide('Семь профилей потребления','Доли расходов в среднем за июль–декабрь 2024, %.');const cats=['Продовольствие','Здоровье','Маркетплейсы','Общественное питание','Транспорт','Прочие расходы'];let sorted=[...p].sort((a,b)=>b['Продовольствие']-a['Продовольствие']);chart(sl,'bar',sorted.map(r=>'G'+r.cluster),cats.map((cat,j)=>({name:cat==='Общественное питание'?'Общепит':cat,values:sorted.map(r=>r[cat]*100),fill:colors[j]})),{barOptions:{direction:'bar',grouping:'stacked'},xAxis:{title:'Группа'},yAxis:{title:'Доля расходов, %',min:0,max:100}});txt(sl,'G11 — продовольствие и маркетплейсы. G15 — диверсифицированный сервисный профиль.',65,625,1120,40,20);sl.speakerNotes.textFrame.setText(src+' Семь групп: G1 транспорт и общепит; G5 умеренная доля маркетплейсов; G9 маркетплейсы и услуги; G11 продовольствие и маркетплейсы; G13 общепит и здоровье; G14 продовольственный смешанный; G15 диверсифицированный сервисный. Названия описательные, не отраслевая классификация.');
sl=slide('Доля маркетплейсов выросла на 4,24 п. п.','Среднее по территориям, без взвешивания населением. Исходные месячные доли.');chart(sl,'bar',['2023','2024'],[{name:'Маркетплейсы',values:[i.marketplace_2023_mean_pct,i.marketplace_2024_mean_pct],fill:green}],{barOptions:{direction:'column',grouping:'clustered'},hasLegend:false,dataLabels:{showValue:true,position:'outEnd',numberFormatCode:'0.0'},yAxis:{title:'Доля расходов, %'}});txt(sl,'Рост в 99,6% пар «территория–месяц» при сравнении одинаковых месяцев год к году.',65,625,1120,43,23,true);sl.speakerNotes.textFrame.setText(src+' Среднее11.7036058% в2023,15.9388058% в2024. Прирост4.2352п.п., положителен99.5701% из24192пар. Причины роста не идентифицированы.');
sl=slide('Методы выигрывают по разным критериям','Одинаковые признаки, одна сеть и K = 7. Декабрь 2024.');chart(sl,'bar',['Leiden','K-means','Ward'],[{name:'SW, разделение профилей',values:s.latest_metrics.map(r=>r.SW),fill:'#3D64B1'},{name:'AVI, изоляция групп',values:s.latest_metrics.map(r=>r.AVI),fill:green}],{barOptions:{direction:'column',grouping:'clustered'},dataLabels:{showValue:true,position:'outEnd',numberFormatCode:'0.000'},yAxis:{title:'Значение индекса'}});txt(sl,'K-means лучше по SW и CH. Leiden лучше по AVI, MQ, Q и выбранному S_Dbw.',65,625,1120,45,23,true);sl.speakerNotes.textFrame.setText(src+' Все шесть требуемых ICVI посчитаны:SW,CH,S_Dbw,AVI,AVU,MQ. Q отдельно. S_Dbw:Halkidi,s-dbw0.4.0,nearest_centr=True. MQ — средняя внутренняя минус средняя внешняя плотность. Случайный baseline сохраняет размеры групп,20перестановок.');
sl=slide('Состав групп меняется во времени','Jaccard и венгерский алгоритм сопоставляют группы соседних месяцев.');let st24=st.filter(r=>r.date.startsWith('2024'));chart(sl,'line',st24.map(r=>r.date),[{name:'ARI соседних месяцев',values:st24.map(r=>r.ARI),line:{fill:green,width:3}},{name:'Доля переходов',values:st24.map(r=>r.switch_share),line:{fill:'#D78F38',width:3}}],{lineOptions:{smooth:false},yAxis:{title:'Доля / индекс',min:0,max:1}});txt(sl,`За все 23 перехода: средний ARI = ${s.mean_monthly_ARI.toFixed(3)}, смена группы = ${(s.mean_switch_share*100).toFixed(1)}%.`,65,625,1120,43,23);sl.speakerNotes.textFrame.setText(src+' Переходы сохраняют все потоки, включая разделение и объединение. ARI не зависит от числовых меток. Смена метки может отражать не изменение реального профиля, а изменение границы алгоритма.');
sl=slide('Устойчивое ядро и пограничные территории','12 запусков с разными seed. Поддержка метки не ниже 80%.');chart(sl,'bar',['Декабрь 2024'],[{name:'Поддержка ≥ 80%',values:[i.core_count],fill:green,dataLabelOverrides:[{idx:0,text:String(i.core_count),showValue:false,textStyle:{typeface:family,fontSize:22,fill:'#FFFFFF'}}]},{name:'Пограничные',values:[i.boundary_count],fill:'#D78F38',dataLabelOverrides:[{idx:0,text:String(i.boundary_count),showValue:false,textStyle:{typeface:family,fontSize:22,fill:'#FFFFFF'}}]}],{barOptions:{direction:'bar',grouping:'stacked'},dataLabels:{showValue:true,position:'center',textStyle:{typeface:family,fontSize:22,fill:'#FFFFFF'}},xAxis:{title:'Месяц'},yAxis:{title:'Количество территорий',min:0,max:2016}});txt(sl,`Устойчивое ядро: ${i.core_count} МО (${(s.core_share*100).toFixed(1)}%).\nСредний ARI подвыборок по 80% МО: ${s.stability_subsample_mean.toFixed(3)}.`,65,600,1120,70,24);sl.speakerNotes.textFrame.setText(src+' Seed_support — доля совпавших меток после Jaccard-сопоставления, не вероятность истинного экономического класса. Подвыборки без возвращения,12повторов; это не классический bootstrap.');
sl=slide('Группы различаются доступностью рынков','Внешний показатель не участвовал в признаках и подборе кластеров.');let ma=s.external.market_access;chart(sl,'bar',ma.map(r=>'G'+r.cluster),[{name:'Медиана доступности рынков',values:ma.map(r=>r.median),fill:green}],{barOptions:{direction:'column',grouping:'clustered'},hasLegend:false,dataLabels:{showValue:true,position:'outEnd',numberFormatCode:'0.0'},yAxis:{title:'Индекс'}});txt(sl,'Покрытие: 2 004 МО. Описательный размер эффекта ε² = 0,380. Причинный вывод не следует.',65,625,1120,43,22);sl.speakerNotes.textFrame.setText(src+' Медианы G5=221.7,G13=524,G15=626.4. KruskalH=764.515, пространственная зависимость ограничивает p-value. Дорожные расстояния:медиана877.1км экономические рёбра,1711.05км случайные пары на наблюдаемом покрытии.');
sl=slide('Применение и ограничения','Профиль помогает подобрать аналоги территории и проверить изменение спроса.');txt(sl,'Выбор территории и её экономических соседей\nИстория исходных долей и среднего профиля\nВсе переходы между группами в Sankey\nПроверка поддержки и чувствительности параметров',65,235,1120,215,29);txt(sl,'Расходы номинальные и модельные. Группы перекрываются.\nПереход не доказывает шок. Полная панель не охватывает все МО России.\nНаименования и карта границ в текущей версии не подключены.',65,500,1120,140,25,false,muted);
sl=slide('Воспроизводимое решение','Исходные данные, контрольные суммы и все результаты включены в пакет.');txt(sl,'config.yaml — гиперпараметры\nrequirements.txt — фиксированные версии\nsrc/pipeline.py — весь расчёт\ntests/ — аналитические проверки графов и панели\ndocs/interactive.html — автономная визуализация\ndocs/methodology_ru.pdf — русский отчёт',65,235,1100,300,28);txt(sl,'Методология и ограничения раскрыты. Экономические выводы отделены от гипотез.',65,590,1120,56,25,true,green);sl.speakerNotes.textFrame.setText(src+' Ссылки на публикации и точные определения показателей в методологическом отчёте. Код MIT, данные и производные результатыCC BY-SA4.0. GitHubрепозиторий требуется для подачи; исходники готовы к размещению.');
await fs.mkdir(path.join(workspaceDir,'build'),{recursive:true});
const candidatePath=path.join(workspaceDir,'build/candidate.pptx');await(await PresentationFile.exportPptx(P)).save(candidatePath);
const FINAL_PPTX=path.join(workspaceDir,'docs/presentation.pptx');
await finalizePresentation({workspaceDir,candidatePath,finalPath:FINAL_PPTX.replace('.pptx','_final2.pptx'),pythonExecutable:process.env.CODEX_PRIMARY_RUNTIME_PYTHON,integrityValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL_DIR,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],requiredNativeChartOwnerSlides:[5,6,7,8,9,10],fontPolicy:{basis:'design',families:[family]},verifyArtifactToolImport:true,materializeLiteralChartWorkbooks:true,receiptPath:path.join(workspaceDir,'build/deck-validation-final2.json')});
for(let j=0;j<P.slides.items.length;j++){let preview=await P.export({slide:P.slides.items[j],format:'png',scale:1});await fs.writeFile(path.join(workspaceDir,`build/slide-${String(j+1).padStart(2,'0')}.png`),new Uint8Array(await preview.arrayBuffer()));}
console.log('Deck complete');
